# Generated by Django 5.1.4 on 2026-04-20 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('crop_type', models.CharField(choices=[('Corn', 'Corn'), ('Wheat', 'Wheat'), ('Soybeans', 'Soybeans'), ('Rice', 'Rice'), ('Barley', 'Barley'), ('Other', 'Other')], max_length=50)),
                ('planting_date', models.DateField(auto_now_add=True)),
                ('current_stage', models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Ready', 'Ready'), ('Harvested', 'Harvested')], default='Planted', max_length=20)),
                ('old_stage', models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Ready', 'Ready'), ('Harvested', 'Harvested')], default='Planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
                ('created_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fields',
            },
        ),
    ]
